# Generated by Django 4.1.3 on 2023-01-28 07:10

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Muallif')),
                ('name', models.CharField(max_length=50, verbose_name='Imtihon nomi')),
                ('science_name', models.CharField(max_length=50, verbose_name='Fan nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('time_limit', models.IntegerField(default=1, verbose_name='Har bir test uchun ajratilgan vaqt(minut)')),
                ('questions_count', models.IntegerField(default=20, verbose_name="O'quvchiga chiquvchi testlar soni(ta)")),
                ('status', models.CharField(choices=[('open', 'Barcha uchun ochiq'), ('close', 'Barcha uchun yopiq')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuizExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=quiz.models.user_directory_path, verbose_name='Fayl')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt:")),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exams', verbose_name='Imtihon nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer_a', models.CharField(max_length=200, verbose_name='A javob')),
                ('answer_b', models.CharField(max_length=200, verbose_name='B javob')),
                ('answer_c', models.CharField(max_length=200, verbose_name='C javob')),
                ('answer_d', models.CharField(max_length=200, verbose_name='D javob')),
                ('answer', models.CharField(choices=[('answer_a', 'A javob'), ('answer_b', 'B javob'), ('answer_c', 'C javob'), ('answer_d', 'D javob')], default='answer_c', max_length=10, verbose_name='Javob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exams', verbose_name='Imtihon')),
            ],
        ),
    ]
