# Generated by Django 4.1.3 on 2023-01-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='status',
            field=models.CharField(choices=[('open', 'Barcha uchun ochiq'), ('close', 'Barcha uchun yopiq')], default='open', max_length=20),
        ),
    ]
