# Generated by Django 4.1.3 on 2022-12-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imtihon nomi')),
                ('science_name', models.CharField(max_length=50, verbose_name='Fan nomi')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='exam',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quiz.exams', verbose_name='Imtihon'),
            preserve_default=False,
        ),
    ]
