# Generated by Django 4.1.3 on 2023-02-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary_user',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fayl manzili'),
        ),
    ]
