# Generated by Django 4.1.3 on 2022-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Asadbek', max_length=50, verbose_name='Ism'),
            preserve_default=False,
        ),
    ]
