# Generated by Django 4.1.3 on 2022-12-19 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_exams_created_at_exams_questions_count_and_more'),
        ('accounts', '0008_alter_results_time_out_alter_results_wrong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vaqtinchalik foydalanuvchi ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Vaqtinchalik foydalanuvchi familiyasi')),
                ('correct', models.IntegerField(default=0, verbose_name="To'g'ri javob")),
                ('wrong', models.IntegerField(default=0, verbose_name="Noto'gri javob")),
                ('time_out', models.IntegerField(blank=True, null=True, verbose_name='Vaqt')),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exams', verbose_name='Imtihon nomi')),
            ],
        ),
    ]
