# Generated by Django 4.1.3 on 2022-12-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_temporary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary_user',
            name='time_out',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Vaqt'),
        ),
    ]
