# Generated by Django 4.1.3 on 2022-12-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_temporary_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vaqtinchalik foydalanuvchi ismi'),
        ),
        migrations.AlterField(
            model_name='temporary_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vaqtinchalik foydalanuvchi familiyasi'),
        ),
    ]
